---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mcp-date-time
  labels:
    app: mcp-date-time
spec:
  output:
    to:
      kind: ImageStreamTag
      name: mcp-date-time:latest
  source:
    type: Git
    git:
      uri: https://github.com/mfdii/mcp-date-time.git
      ref: mcp-v2-migration
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  triggers:
  - type: ConfigChange
