---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mcp-date-time
  labels:
    app: mcp-date-time
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: mcp-date-time
    weight: 100
  wildcardPolicy: None
